# Generated by Django 5.1.7 on 2025-07-25 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('profiles', '0001_initial'),
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionbooking',
            name='mentor',
            field=models.ForeignKey(default=1, limit_choices_to={'role': 'mentor'}, on_delete=django.db.models.deletion.CASCADE, related_name='mentored_sessions', to='profiles.userprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sessionbooking',
            name='learner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sessionbooking',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_booked', to='skills.skill'),
        ),
    ]
