# Generated by Django 5.2.3 on 2025-08-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_sessionbooking_mentor_alter_sessionbooking_learner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionbooking',
            name='is_confirmed',
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='duration',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='skill_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('rescheduled', 'Rescheduled')], default='pending', max_length=15),
        ),
    ]
