# Generated by Django 5.1.7 on 2025-08-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_sessionbooking_is_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionbooking',
            name='notes_available',
            field=models.BooleanField(default=False),
        ),
    ]
