# Generated by Django 6.0.6 on 2026-06-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_sessionbooking_notes_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionbooking',
            name='meeting_link',
            field=models.URLField(blank=True, help_text='Optional meeting/join URL for the session', null=True),
        ),
    ]
