# Generated by Django 6.0.6 on 2026-06-10 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_sessionbooking_meeting_link'),
        ('profiles', '0002_remove_userprofile_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionbooking',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='mentor_profile',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'coach'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to='profiles.userprofile'),
        ),
        migrations.AlterField(
            model_name='sessionbooking',
            name='mentor',
            field=models.ForeignKey(limit_choices_to={'role': 'coach'}, on_delete=django.db.models.deletion.CASCADE, related_name='mentored_sessions', to='profiles.userprofile'),
        ),
    ]
