# Generated by Django 6.0.6 on 2026-06-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_sessionbooking_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionbooking',
            name='notes_file',
            field=models.FileField(blank=True, null=True, upload_to='session_notes/'),
        ),
    ]
