# Generated by Django 6.0.6 on 2026-06-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_sessionbooking_notes_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('rescheduled', 'Rescheduled'), ('completed', 'Completed')], default='pending', max_length=15),
        ),
    ]
