# Generated by Django 5.2.7 on 2026-06-14 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_add_milestone'),
        ('profiles', '0003_userprofile_timezone'),
        ('skills', '0003_alter_skill_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('held', 'Held'), ('booked', 'Booked'), ('blocked', 'Blocked')], default='open', max_length=10)),
                ('source', models.CharField(choices=[('auto', 'Auto-generated'), ('manual', 'Manual')], default='auto', max_length=10)),
                ('held_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(limit_choices_to={'role': 'coach'}, on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='profiles.userprofile')),
                ('skill', models.ForeignKey(blank=True, help_text='Optional: restrict this slot to a specific skill. Null = any skill.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='skills.skill')),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='slot',
            field=models.OneToOneField(blank=True, help_text='The bookable time slot this session occupies (slot-based booking).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking', to='bookings.timeslot'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['coach', 'status', 'start_datetime'], name='bookings_ti_coach_i_5d0400_idx'),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(fields=('coach', 'start_datetime', 'end_datetime'), name='unique_coach_slot'),
        ),
    ]
