# Generated by Django 6.0.6 on 2026-06-15 07:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_timeslot_held_by'),
        ('profiles', '0004_userprofile_booking_horizon_days_and_more'),
        ('skills', '0004_availability_buffer_minutes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('capacity', models.PositiveIntegerField(default=10, help_text='Maximum number of participants.', validators=[django.core.validators.MinValueValidator(1)])),
                ('price_per_seat', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('meeting_link', models.URLField(blank=True, help_text='Shared join URL for all participants.', null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('full', 'Full'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(limit_choices_to={'role': 'coach'}, on_delete=django.db.models.deletion.CASCADE, related_name='group_sessions', to='profiles.userprofile')),
                ('skill', models.ForeignKey(blank=True, help_text='Optional: link this session to a skill/offering.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_sessions', to='skills.skill')),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='GroupEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('held', 'Held'), ('booked', 'Booked'), ('cancelled', 'Cancelled')], default='held', max_length=10)),
                ('held_until', models.DateTimeField(blank=True, null=True)),
                ('payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='unpaid', max_length=20)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_enrollments', to=settings.AUTH_USER_MODEL)),
                ('group_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='bookings.groupsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='groupsession',
            index=models.Index(fields=['coach', 'status', 'start_datetime'], name='bookings_gr_coach_i_d57337_idx'),
        ),
        migrations.AddConstraint(
            model_name='groupenrollment',
            constraint=models.UniqueConstraint(fields=('group_session', 'learner'), name='unique_group_enrollment'),
        ),
    ]
