# Generated by Django 6.0.6 on 2026-06-27 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_groupsession_groupenrollment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='bookings.timeslot')),
            ],
            options={
                'ordering': ['-invited_at'],
                'constraints': [models.UniqueConstraint(fields=('slot', 'email'), name='unique_slot_invite')],
            },
        ),
    ]
