# Generated by Django 6.0.6 on 2026-06-28 16:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_slotinvite'),
        ('skills', '0004_availability_buffer_minutes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slotinvite',
            options={'ordering': ['-last_sent_at']},
        ),
        migrations.AddField(
            model_name='slotinvite',
            name='last_sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='slotinvite',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='slotinvite',
            name='sent_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='slotinvite',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot_invites', to='skills.skill'),
        ),
    ]
