# Generated by Django 6.0.6 on 2026-07-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_habit_habitcheckin'),
        ('resources', '0005_resourcefolder_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotinvite',
            name='attached_resources',
            field=models.ManyToManyField(blank=True, related_name='slot_invites', to='resources.resource'),
        ),
    ]
