# Generated by Django 6.0.6 on 2026-07-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_slotinvite_attached_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionbooking',
            name='thankyou_sent',
            field=models.BooleanField(default=False),
        ),
    ]
