# Generated by Django 6.0.6 on 2026-07-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0019_sessionsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionbooking',
            name='client_joined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='coach_joined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessionbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('rescheduled', 'Rescheduled'), ('completed', 'Completed'), ('no_show', 'No Show')], default='pending', max_length=15),
        ),
    ]
