# Generated by Django 6.0.6 on 2026-07-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0020_sessionbooking_client_joined_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionbooking',
            name='client_admit_status',
            field=models.CharField(blank=True, choices=[('', 'None'), ('requested', 'Requested'), ('admitted', 'Admitted'), ('denied', 'Denied')], default='', max_length=10),
        ),
    ]
