# Generated by Django 6.0.6 on 2026-07-14 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0021_sessionbooking_client_admit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionbooking',
            name='guest_link_active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CallGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_uid', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('admitted', 'Admitted'), ('denied', 'Denied')], default='requested', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_guests', to='bookings.sessionbooking')),
            ],
        ),
    ]
