# Generated by Django 6.0.7 on 2026-07-17 07:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0022_sessionbooking_guest_link_active_callguest'),
        ('profiles', '0007_userprofile_restricted_to_skill'),
        ('skills', '0004_availability_buffer_minutes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sessionbooking',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('payment_intent_id', None), _negated=True), models.Q(('payment_intent_id', ''), _negated=True)), fields=('payment_intent_id',), name='unique_payment_intent_per_booking'),
        ),
    ]
