# Generated by Django 6.0.7 on 2026-07-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0023_sessionbooking_unique_payment_intent_per_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('rescheduled', 'Rescheduled'), ('completed', 'Completed'), ('no_show', 'No Show'), ('held_offline', 'Held off-platform'), ('not_held', 'Did not take place')], default='pending', max_length=15),
        ),
    ]
