# Generated by Django 6.0.7 on 2026-07-28 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0024_alter_sessionbooking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionsummary',
            name='summary_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
