# Generated by Django 6.0.7 on 2026-07-28 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0025_sessionsummary_summary_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionsummary',
            name='reflection_points',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
