# Generated by Django 6.0.7 on 2026-08-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0026_sessionsummary_reflection_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='category',
            field=models.CharField(blank=True, choices=[('nutrition', 'Nutrition & eating'), ('activity', 'Physical activity'), ('sleep', 'Sleep'), ('stress', 'Stress'), ('mindfulness', 'Mindfulness'), ('relationships', 'Relationships & connection'), ('burnout', 'Burnout'), ('balance', 'Work-life balance')], default='', max_length=20),
        ),
    ]
