# Generated by Django 6.0.7 on 2026-08-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0027_habit_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionsummary',
            name='analytics',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sessionsummary',
            name='transcript_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
