# Generated by Django 6.0.7 on 2026-09-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0028_sessionsummary_analytics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionbooking',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
