# Generated by Django 6.0.7 on 2026-09-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0029_sessionbooking_ended_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionbooking',
            name='ai_notes_off',
            field=models.BooleanField(default=False),
        ),
    ]
