"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from backend/.env (secrets, email creds, etc.).
# Values already present in the real environment take precedence over the file.
load_dotenv(BASE_DIR / '.env')


def env_bool(key, default=False):
    """Read a boolean-ish env var ('1', 'true', 'yes' → True)."""
    val = os.environ.get(key)
    if val is None:
        return default
    return val.strip().lower() in ('1', 'true', 'yes', 'on')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Falls back to the previous hardcoded key so existing deploys keep working
# until a SECRET_KEY is supplied via .env.
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-faqs37dl@2c#d8(ufxdpqjk_-9pf_xge6)npig%5&48qy_b1ii',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['129.121.115.149', 'dr-nath.com', 'www.dr-nath.com', 'localhost', '127.0.0.1']

# Required for the Django admin login POST over HTTPS behind nginx.
CSRF_TRUSTED_ORIGINS = ['https://dr-nath.com', 'https://www.dr-nath.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'profiles',
    'skills',
    'bookings',
    'messages.apps.MessagesConfig',
    'resources',
    'notifications',
    'contact',
    'newsletters',
    'assistant',
    'signatures',
    'formbuilder',
    'integrations',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases



DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'skillforge',
        'USER': 'skilluser',
        'PASSWORD': 'banned1234',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
  'DEFAULT_AUTHENTICATION_CLASSES': (
      'rest_framework_simplejwt.authentication.JWTAuthentication',
  ),
  'DEFAULT_THROTTLE_CLASSES': [],
  'DEFAULT_THROTTLE_RATES': {
      # Per-IP cap for the public AI assistant endpoint (paid API behind it).
      'assistant': '20/min',
      # Per-IP cap on login attempts — slows brute-force / username enumeration.
      'login': '10/min',
  },
}

# JWT session lifetimes. The library defaults (5-min access token) were logging
# users out mid-task — e.g. "Could not send the invite" was actually an expired
# session. Keep coaches/clients signed in through a working session.
from datetime import timedelta  # noqa: E402
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=12),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': True,
}

CORS_ALLOW_ALL_ORIGINS = True

AUTH_USER_MODEL = 'profiles.CustomUser'

STRIPE_SECRET_KEY = os.environ.get(
    'STRIPE_SECRET_KEY',
    'sk_test_51RCasKQOwqqD0Bo5Wo1iYXwWjvY5rXuJwMOPgExENTNgCU9obOs4olQSQFcwbNHZr5cracOEFs4AYBTEIPE884JR003i1o5WXv',
)
STRIPE_PUBLISHABLE_KEY = os.environ.get(
    'STRIPE_PUBLISHABLE_KEY',
    'pk_test_51RCasKQOwqqD0Bo5Lzoz0xt4hMfh2bmrua5Vo3TchUsnI5ZpgDV1Pg7pZUlmBd0soZSOrkJLSTAWkMisLNxH1Pru00v8URzIRH',
)

# ─── AI Virtual Assistant ─────────────────────────────────────────────────────
# Provider-agnostic website chatbot. AI_PROVIDER selects the backend:
#   'auto'      → use whichever API key is set (Anthropic preferred, then OpenAI)
#   'anthropic' → force Anthropic (needs ANTHROPIC_API_KEY)
#   'openai'    → force OpenAI (needs OPENAI_API_KEY)
# With no key set, the endpoint returns a graceful "not configured" reply.
AI_PROVIDER = os.environ.get('AI_PROVIDER', 'auto')
ANTHROPIC_API_KEY = os.environ.get('ANTHROPIC_API_KEY', '')
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY', '')
# Optional model override. Defaults are chosen per provider in assistant/services.py.
ASSISTANT_MODEL = os.environ.get('ASSISTANT_MODEL', '')

# ─── LiveKit (video calls) ────────────────────────────────────────────────────
# Used to mint room access tokens. The frontend connects to LIVEKIT_URL with a
# token issued by the backend (see bookings/livekit_views.py).
LIVEKIT_URL = os.environ.get('LIVEKIT_URL', '')
LIVEKIT_API_KEY = os.environ.get('LIVEKIT_API_KEY', '')
LIVEKIT_API_SECRET = os.environ.get('LIVEKIT_API_SECRET', '')
# How long an issued room token stays valid (seconds).
LIVEKIT_TOKEN_TTL = int(os.environ.get('LIVEKIT_TOKEN_TTL', '21600'))  # 6 hours

# ─── Server-side transcription (E7 Phase 3) ───────────────────────────────────
# The optional transcription worker (backend/transcription_worker.py) joins each
# session room, transcribes all participants server-side (covers every browser),
# and stores the AI summary. It runs as a SEPARATE process/venv — these settings
# just tell it which STT provider + key to use. Leave TRANSCRIPTION_ENABLED off
# until a key is set; the browser MVP (Phase 2) keeps working regardless.
TRANSCRIPTION_ENABLED = os.environ.get('TRANSCRIPTION_ENABLED', 'false').lower() == 'true'
STT_PROVIDER = os.environ.get('STT_PROVIDER', 'deepgram').lower()  # 'deepgram' | 'openai'
STT_LANGUAGE = os.environ.get('STT_LANGUAGE', 'en')                # e.g. 'en', 'fr'
DEEPGRAM_API_KEY = os.environ.get('DEEPGRAM_API_KEY', '')
DEEPGRAM_MODEL = os.environ.get('DEEPGRAM_MODEL', 'nova-2')
# OpenAI Whisper STT reuses OPENAI_API_KEY (already read for the assistant).

# ─── Google Calendar integration (OAuth 2.0) ──────────────────────────────────
# Per-coach two-way sync. Credentials come from Google Cloud Console (git-ignored
# .env). Redirect URI must match exactly what's registered on the OAuth client.
GOOGLE_CLIENT_ID = os.environ.get('GOOGLE_CLIENT_ID', '')
GOOGLE_CLIENT_SECRET = os.environ.get('GOOGLE_CLIENT_SECRET', '')
GOOGLE_OAUTH_REDIRECT_URI = os.environ.get(
    'GOOGLE_OAUTH_REDIRECT_URI', 'https://dr-nath.com/api/integrations/google/callback/'
)
GOOGLE_CALENDAR_SCOPES = [
    'https://www.googleapis.com/auth/calendar.events',
    'https://www.googleapis.com/auth/calendar.readonly',
]

# Grace window (minutes) a call stays joinable past its scheduled end. Mirrors
# SESSION_GRACE_MS on the frontend — keep the two in sync.
SESSION_GRACE_MINUTES = int(os.environ.get('SESSION_GRACE_MINUTES', '10'))

# ─── Email configuration ──────────────────────────────────────────────────────
# All values come from backend/.env. EMAIL_BACKEND defaults to console (prints
# emails to the Daphne log) so the app works before real SMTP creds are set;
# set EMAIL_BACKEND to the SMTP backend in .env to actually send mail.
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend',
)
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = env_bool('EMAIL_USE_TLS', True)
EMAIL_USE_SSL = env_bool('EMAIL_USE_SSL', False)
EMAIL_TIMEOUT = int(os.environ.get('EMAIL_TIMEOUT', '15'))
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'Dr. Nath Coaching <no-reply@dr-nath.com>')
# Public site URL used to build links inside emails.
SITE_URL = os.environ.get('SITE_URL', 'https://dr-nath.com')

INSTALLED_APPS += ['channels']

ASGI_APPLICATION = 'config.routing.application'

# For local dev we run a single daphne process, so the in-memory channel layer
# is sufficient and avoids the intermittent Redis read-timeouts that were
# killing WebSocket connections (and thus WebRTC signaling) mid-session.
# Switch back to channels_redis.core.RedisChannelLayer for multi-process/prod.
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}