# Generated by Django 6.0.6 on 2026-06-10 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_userprofile_availability_and_more'),
        ('skills', '0002_alter_skill_unique_together_skill_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='profile',
            field=models.ForeignKey(limit_choices_to={'role': 'coach'}, on_delete=django.db.models.deletion.CASCADE, related_name='offered_skills', to='profiles.userprofile'),
        ),
    ]
