# Generated by Django 6.0.6 on 2026-06-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_alter_skill_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='buffer_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Gap left between consecutive slots, in minutes.'),
        ),
        migrations.AddField(
            model_name='availability',
            name='slot_duration',
            field=models.PositiveIntegerField(default=60, help_text='Length of each generated slot, in minutes.'),
        ),
    ]
