# Generated by Django 6.0.7 on 2026-08-03 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_availability_buffer_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='is_chemistry',
            field=models.BooleanField(default=False),
        ),
    ]
