# Generated by Django 6.0.7 on 2026-08-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0005_skill_is_chemistry'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
