# Generated by Django 6.0.7 on 2026-09-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0006_skill_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='max_bookings_per_client',
            field=models.PositiveIntegerField(blank=True, help_text='How many sessions of this offering one client may book. Blank = no limit.', null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='max_total_bookings',
            field=models.PositiveIntegerField(blank=True, help_text='Stop accepting bookings once this many have been made. Blank = no limit.', null=True),
        ),
    ]
