# Generated by Django 6.0.7 on 2026-09-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0007_skill_booking_caps'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='requires_participation_code',
            field=models.BooleanField(default=False),
        ),
    ]
