# Generated by Django 6.0.6 on 2026-07-07 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0019_sessionsummary'),
        ('profiles', '0007_userprofile_restricted_to_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalendarAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_email', models.EmailField(blank=True, default='', max_length=254)),
                ('calendar_id', models.CharField(default='primary', max_length=255)),
                ('refresh_token', models.TextField(blank=True, default='')),
                ('access_token', models.TextField(blank=True, default='')),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('sync_bookings_out', models.BooleanField(default=True, help_text='Create/update platform bookings as events on this calendar.')),
                ('block_busy_times', models.BooleanField(default=True, help_text="Hide platform slots that clash with this calendar's busy times.")),
                ('is_active', models.BooleanField(default=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_calendar', to='profiles.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarEventLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_event_id', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_links', to='bookings.sessionbooking')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_links', to='integrations.googlecalendaraccount')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('booking', 'account'), name='unique_booking_account_event')],
            },
        ),
    ]
