# Generated by Django 6.0.6 on 2026-06-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_messages', '0003_message_attachment_message_attachment_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='chat_attachments/'),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='attachment_size',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='content_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
