# Generated by Django 6.0.7 on 2026-08-03 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formbuilder', '0001_initial'),
        ('skills', '0005_skill_is_chemistry'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtemplate',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_forms', to='skills.skill'),
        ),
    ]
