# Generated by Django 6.0.7 on 2026-09-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formbuilder', '0002_formtemplate_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtemplate',
            name='auto_assign_on_signup',
            field=models.BooleanField(default=False, help_text='Send automatically to every client who registers.'),
        ),
    ]
