# Generated by Django 6.0.6 on 2026-07-02 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0005_userprofile_linkedin_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True, help_text='Optional note shown to the client.')),
                ('file', models.FileField(help_text='The original document to sign.', upload_to='resources/agreements/')),
                ('signed_file', models.FileField(blank=True, help_text='Generated PDF with both signatures.', null=True, upload_to='resources/agreements/signed/')),
                ('status', models.CharField(choices=[('sent', 'Awaiting client signature'), ('client_signed', 'Awaiting coach counter-signature'), ('completed', 'Completed'), ('declined', 'Declined')], default='sent', max_length=16)),
                ('client_signature', models.CharField(blank=True, max_length=200)),
                ('client_signed_at', models.DateTimeField(blank=True, null=True)),
                ('client_signed_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('coach_signature', models.CharField(blank=True, max_length=200)),
                ('coach_signed_at', models.DateTimeField(blank=True, null=True)),
                ('coach_signed_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('decline_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_documents', to=settings.AUTH_USER_MODEL)),
                ('coach', models.ForeignKey(limit_choices_to={'role': 'coach'}, on_delete=django.db.models.deletion.CASCADE, related_name='sent_signature_documents', to='profiles.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['coach', 'status'], name='signatures__coach_i_7b4c00_idx'), models.Index(fields=['client', 'status'], name='signatures__client__0d78a5_idx')],
            },
        ),
    ]
