# Generated by Django 6.0.7 on 2026-07-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='source',
            field=models.CharField(choices=[('modal', 'Pop-up modal'), ('band', 'Homepage band'), ('client', 'Registered client'), ('other', 'Other')], default='other', max_length=10),
        ),
    ]
