# Generated by Django 6.0.7 on 2026-10-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0002_alter_newslettersubscriber_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='edition',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
