# Generated by Django 6.0.6 on 2026-06-15 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0012_groupsession_groupenrollment_and_more'),
        ('profiles', '0004_userprofile_booking_horizon_days_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(limit_choices_to={'role': 'coach'}, on_delete=django.db.models.deletion.CASCADE, related_name='resource_folders', to='profiles.userprofile')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='resources/')),
                ('file_size', models.PositiveBigIntegerField(blank=True, help_text='Size in bytes.', null=True)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('visibility', models.CharField(choices=[('all_clients', 'All my coachees'), ('specific', 'Specific clients'), ('group', 'A group session')], default='all_clients', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(limit_choices_to={'role': 'coach'}, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='profiles.userprofile')),
                ('group_session', models.ForeignKey(blank=True, help_text="Used when visibility is 'group'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='bookings.groupsession')),
                ('shared_clients', models.ManyToManyField(blank=True, help_text="Used when visibility is 'specific'.", related_name='shared_resources', to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='resources.resourcefolder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='resourcefolder',
            constraint=models.UniqueConstraint(fields=('coach', 'name'), name='unique_folder_per_coach'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['coach', 'visibility'], name='resources_r_coach_i_04c9bf_idx'),
        ),
    ]
