# Generated by Django 6.0.6 on 2026-06-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='visibility',
            field=models.CharField(choices=[('all_platform', 'All clients (including those with no booking)'), ('all_clients', 'Clients with at least one booking (my coachees)'), ('specific', 'Specific clients'), ('group', 'A group session')], default='all_clients', max_length=12),
        ),
    ]
