# Generated by Django 6.0.6 on 2026-06-17 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_userprofile_booking_horizon_days_and_more'),
        ('resources', '0002_alter_resource_visibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('note', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='submissions/')),
                ('file_size', models.PositiveBigIntegerField(blank=True, help_text='Size in bytes.', null=True)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('reviewed', 'Reviewed')], default='submitted', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
                ('coach', models.ForeignKey(limit_choices_to={'role': 'coach'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_submissions', to='profiles.userprofile')),
                ('in_response_to', models.ForeignKey(blank=True, help_text='Optional: the resource/assignment this responds to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='resources.resource')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['coach', 'status', '-created_at'], name='resources_c_coach_i_3113e6_idx'), models.Index(fields=['client', '-created_at'], name='resources_c_client__4616e2_idx')],
            },
        ),
    ]
