# Generated by Django 6.0.6 on 2026-06-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_clientsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='link_url',
            field=models.URLField(blank=True, help_text='External link, used instead of a file.', max_length=500),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resources/'),
        ),
    ]
