# Generated by Django 6.0.7 on 2026-08-03 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_resourcefolder_client'),
        ('skills', '0004_availability_buffer_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='skills.skill'),
        ),
    ]
