# Generated by Django 5.2.7 on 2026-06-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_userprofile_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(default='UTC', help_text="IANA timezone name, e.g. 'America/New_York'. Used to display slots.", max_length=64),
        ),
    ]
