# Generated by Django 6.0.6 on 2026-06-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userprofile_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='booking_horizon_days',
            field=models.PositiveIntegerField(default=30, help_text='How many days into the future clients may book.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='min_notice_hours',
            field=models.PositiveIntegerField(default=12, help_text='Minimum lead time, in hours, required before a session can start.'),
        ),
    ]
