# Generated by Django 6.0.6 on 2026-07-02 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_userprofile_booking_horizon_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, default='', max_length=300),
        ),
    ]
