# Generated by Django 6.0.6 on 2026-07-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_userprofile_linkedin_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='min_notice_hours',
            field=models.PositiveIntegerField(default=24, help_text='Minimum lead time, in hours, required before a session can start.'),
        ),
    ]
