# Generated by Django 6.0.6 on 2026-07-06 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_userprofile_min_notice_hours'),
        ('skills', '0004_availability_buffer_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='restricted_to_skill',
            field=models.ForeignKey(blank=True, help_text='If set, this client can only book this offering.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restricted_clients', to='skills.skill'),
        ),
    ]
