# Generated by Django 6.0.7 on 2026-09-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_userprofile_restricted_to_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='resources_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
