# Generated by Django 6.0.7 on 2026-09-28 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_min_notice_default_12'),
        ('skills', '0007_skill_booking_caps'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='share_with_organisation',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ParticipationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('organisation', models.CharField(max_length=200)),
                ('contact_name', models.CharField(blank=True, max_length=150)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('total_sessions', models.PositiveIntegerField(default=20)),
                ('max_per_client', models.PositiveIntegerField(default=4)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(limit_choices_to={'role': 'coach'}, on_delete=django.db.models.deletion.CASCADE, related_name='participation_codes', to='profiles.userprofile')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participation_codes', to='skills.skill')),
            ],
            options={
                'ordering': ['organisation'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='participation_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='profiles.participationcode'),
        ),
    ]
