# Generated by Django 6.0.7 on 2026-09-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_participation_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='participationcode',
            name='invite_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participationcode',
            name='invite_sent_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='participationcode',
            name='contact_email',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
