# Generated by Django 6.0.7 on 2026-09-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_code_contacts_and_invites'),
    ]

    operations = [
        migrations.AddField(
            model_name='participationcode',
            name='audience',
            field=models.CharField(choices=[('patients', 'Patients'), ('employees', 'Employees'), ('clients', 'Clients')], default='patients', max_length=12),
        ),
    ]
