# skills/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import SkillViewSet, AvailabilityViewSet, PublicSkillListView # <-- All three views must be imported

router = DefaultRouter()
# Specific routes MUST be registered before the empty-prefix SkillViewSet,
# otherwise its detail pattern ^(?P<pk>)/$ swallows 'availabilities/'.
router.register(r'availabilities', AvailabilityViewSet, basename='availability')
# Mentor skill management at the root of /api/skills/
router.register(r'', SkillViewSet, basename='skill')


urlpatterns = [
    # ⭐ This is the correct way to add the ListAPIView URL - must come BEFORE router
    path('public/', PublicSkillListView.as_view(), name='public-skill-list'),
    
    # Include all the URLs generated by the router
    path('', include(router.urls)),
]