# skills/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import SkillViewSet, AvailabilityViewSet, PublicSkillListView # <-- All three views must be imported

router = DefaultRouter()
# This registers the URLs for mentor management at the root of /api/skills/
# Correctly registers the ViewSet
router.register(r'', SkillViewSet, basename='skill')
# This registers the URLs for mentor's availability
# Correctly registers the ViewSet
router.register(r'availabilities', AvailabilityViewSet, basename='availability')


urlpatterns = [
    # ⭐ This is the correct way to add the ListAPIView URL - must come BEFORE router
    path('public/', PublicSkillListView.as_view(), name='public-skill-list'),
    
    # Include all the URLs generated by the router
    path('', include(router.urls)),
]